food/urls.py
from django.urls import path
from . import views

app_name = 'food'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:item_id>/', views.detail, name='detail'),
    path('add/', views.create_item, name='create_item'),
    path('update/<int:id>/', views.update_item, name='update_item'),
    path('delete/<int:id>/', views.delete_item, name='delete_item'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from users import views as user_views
from django.contrib.auth import views as authentication_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include('food.urls')),
    path('register/', user_views.register, name='register'),
    path('login/', authentication_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', authentication_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/', user_views.profilepage, name='profile'),

]



urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='profilepic.jpg', upload_to='profile_pictures')
    location = models.CharField(max_length=100)
    
    def __str__(self):
        return self.user.username

food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name','item_desc','item_price','item_image']

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username','email', 'password1', 'password2']

food/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Item
from django.template import loader
from .forms import ItemForm
# Create your views here.

def index(request):
    item_list = Item.objects.all()
    context = {
        'item_list': item_list,
    }
    return render(request,'food/index.html',context)

def detail(request,item_id):
    item = Item.objects.get(pk=item_id)
    context = {
        'item': item,
    }
    return render(request,'food/detail.html',context)

def create_item(request):
    form = ItemForm(request.POST or None)
    context = {'form':form}

    if form.is_valid():
        form.save()
        return redirect('food:index')

    return render(request,'food/item-form.html',context)

def update_item(request,id):
    item = Item.objects.get(id=id)
    form = ItemForm(request.POST or None, instance=item)
    context = {
        'form': form,
        'item': item,
    }

    if form.is_valid():
        form.save()
        return redirect('food:index')
    
    return render(request,'food/item-form.html/',context)

def delete_item(request,id):
    item = Item.objects.get(id=id)
    context = {'item':item}
    
    if request.method == 'POST':
        item.delete()
        return redirect('food:index')
    
    return render(request,'food/item-delete.html', context)

users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .forms import RegisterForm
from django.contrib.auth.decorators import login_required

# Create your views here.


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request,f'Welcome {username}, your account is created')
            return redirect('login')
    else:
        form = RegisterForm()
    return render(request,'users/register.html',{'form':form})

@login_required
def profilepage(request):
    return render(request,'users/profile.html')

food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "food/style.css" %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Food</title>
</head>
<body>

    <nav class="navbar navbar-dark bg-dark">
        <a href="#" class="navbar-brand">FoodApp</a>

        <div class="navbar">
            <a class="nav-item" href="{% url 'food:create_item' %}">AddItem</a>
            <a class="nav-item" href="#">DeleteItem</a>
            <a class="nav-item" href="#">ViewItem</a>
            {% if user.is_authenticated %}
            <a href = '{% url 'logout' %}'>Logout</a>
            <a href = '{% url 'profile' %}'>Profile</a>
            {% else %}
            <a href = '{% url 'login' %}'>Login</a>
            {% endif %}
        </div>
    </nav>

    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
           {{message}}
        </div>
        {% endfor%}
    {% endif %}
    {% block body%}
    {% endblock%}
      
</body>
</html>

food/templates/food/detail.html
{% extends "food/base.html" %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img class="card" src="{{item.item_image}}">
        </div>
        <div class="col-md-6">
            <h1>{{item.item_name}}</h1>
            <h1>{{item.item_desc}}</h1>
            <h1>${{item.item_price}}</h1>
            <a href="{% url 'food:delete_item' item.id %}">Delete</a>
        </div>
    </div>
</div>

{% endblock %}

food/templates/food/index.html
{% extends "food/base.html" %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Food</title>
</head>
<body>

    {% block body%}

    {% for item in item_list %}

        <div class="row">
            <div class="col-md-3 offset-md-2">
                <img class="card" height="150px" src="{{item.item_image}}"/>
            </div>
            <div class="col-md-4">
                <h3>{{item.item_name}}</h3>
                <h4>{{item.item_desc}}</h4>
                <h5>${{item.item_price}}</h5>
            </div>
            <div class="col-md-2">
                <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Details</a>
            </div>
    {% endfor %}

    {% endblock %}  
</body>
</html>

food/templates/food/item-delete.html
<form method="POST">
    {% csrf_token %}
    <h2>Are you sure you want to delete {{item.item_name}}</h2>
    <button type="submit">Confirm</button>
</form>

food/templates/food/item-form.html
{% extends 'food/base.html' %}

{% block body%}
<form method="POST">
    {% csrf_token %}
    {{form}}
    <button type="submit">Save</button>
</form>
{% endblock %}